<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="aspireggn55" name="Default test" tests="1" failures="1" timestamp="11 May 2017 09:24:27 GMT" time="83.206" errors="0">
  <testcase name="TC_Yatra_Train_048" time="78.585" classname="com.Yatra.TestScript.Trains.Train">
    <failure type="java.lang.AssertionError" message="&amp;lt;b&amp;gt;Actual Result:&amp;lt;/b&amp;gt; Correct amount not displayed on Payment Gateway.">
      <![CDATA[java.lang.AssertionError: <b>Actual Result:</b> Correct amount not displayed on Payment Gateway.
	at org.testng.Assert.fail(Assert.java:94)
	at com.Yatra.Utils.Log.fail(Log.java:546)
	at com.Yatra.Utils.Log.assertThat(Log.java:726)
	at com.Yatra.TestScript.Trains.Train.TC_Yatra_Train_048(Train.java:2814)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- TC_Yatra_Train_048 -->
</testsuite> <!-- Default test -->
